<?php

namespace Xxam\MailclientBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MailaccountuserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailaccountuserRepository extends EntityRepository
{
    
    public function findByUserId($user_id){
        $query = $this->createQueryBuilder('e');
        $query->andWhere('e.user_id',$user_id);

        return $query->getQuery()->getResult();
    }

}
